language: node_js
node_js:
  - "6"
script: 
  - hexo clean && hexo g -d
install:
  - npm install
cache:
  directories:
    - node_modules
branches:
  only:
  - hexo  # 设置自动化部署的分支
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: www
  fqdn: cary.im
  on:
    branch: master
