# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the hexo branch
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          persist-credentials: false
          node-version: '14'

      - name: Install global dependencies
        run: yarn global add hexo-cli

      - name: Install project dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' # Over here!
        run: yarn

      - name: Set user
        run: git config --global user.name 'Cary' && git config --global user.email 'carynihility@gmail.com'

      - name: Generator
        run: yarn run clean && hexo clean && hexo g -d
